const pool = require('./database');
const users = `CREATE TABLE IF NOT EXISTS users(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name NVARCHAR(20) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
phone VARCHAR(10) UNIQUE,
gender VARCHAR(20),
status NVARCHAR(10),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)`
const roles = `CREATE TABLE IF NOT EXISTS roles (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name NVARCHAR(50) NOT NULL,
guard_name VARCHAR(10),
description NVARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)`
const permissions = `CREATE TABLE IF NOT EXISTS permissions (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name NVARCHAR(50) NOT NULL,
guard_name VARCHAR(10),
description NVARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)`
const roles_has_permissions = `CREATE TABLE IF NOT EXISTS roles_has_permissions (
role_id INT UNSIGNED NOT NULL,
permission_id INT UNSIGNED NOT NULL,
PRIMARY KEY(role_id,permission_id),
FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
)`
const addField = `
ALTER TABLE users
ADD COLUMN avatar LONGTEXT,
MODIFY COLUMN status INT DEFAULT(1),
MODIFY COLUMN gender VARCHAR(20)
`
const uhr = `
CREATE TABLE IF NOT EXISTS users_has_roles(
user_id INT UNSIGNED NOT NULL,
role_id INT UNSIGNED NOT NULL,
PRIMARY KEY (user_id,role_id),
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
)`
const category = `
CREATE TABLE IF NOT EXISTS category(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name NVARCHAR(30) NOT NULL,
description NVARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)`
const posts = `
CREATE TABLE IF NOT EXISTS posts(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED UNIQUE NOT NULL,
title NVARCHAR(255) NOT NULL,
slug VARCHAR(255) NOT NULL,
content LONGTEXT NOT NULL,
excerpt VARCHAR(100),
thumbnail VARCHAR(255),
publish TINYINT(1) NOT NULL DEFAULT 2,
published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
meta_title VARCHAR(255),
meta_description VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)`
const comment = `
CREATE TABLE IF NOT EXISTS comment(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED UNIQUE,
post_id INT UNSIGNED UNIQUE,
context NVARCHAR(255) NOT NULL,
parent_id INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
)`
const posts_has_categories = `
CREATE TABLE IF NOT EXISTS posts_has_categories(
post_id INT UNSIGNED NOT NULL,
category_id INT UNSIGNED NOT NULL,
PRIMARY KEY (category_id,post_id),
FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE,
FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
)`
const tags = `
CREATE TABLE IF NOT EXISTS tags (
id INT UNSIGNED PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
slug VARCHAR(255) NOT NULL,
description NVARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)`
const posts_has_tags = `
CREATE TABLE IF NOT EXISTS posts_has_tags(
post_id INT UNSIGNED NOT NULL,
tag_id INT UNSIGNED NOT NULL,
PRIMARY KEY (tag_id,post_id),
FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,
FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
)`
pool.query(posts_has_tags, (err) => {
    if (err) throw err;
    console.log('add data success')
});